#!/usr/bin/env bash
# Regenerate .env.signing by reading the App Store Connect API credentials from
# 1Password (op CLI). PockeDev ships locally with automatic signing and the
# Distribution cert already in the login keychain, so — unlike a CI bootstrap —
# this does NOT import certs or provisioning profiles. It only:
#   1. reads key_id / issuer_id / team_id from your 1Password item,
#   2. materializes the .p8 from the item's base64 field (if not already on disk),
#   3. writes .env.signing.
#
# Setup:
#   1. cp scripts/.env.signing-op.example scripts/.env.signing-op   (gitignored)
#      and point OP_VAULT / OP_ITEM at your 1Password entry.
#   2. eval "$(op signin)"
#   3. ./scripts/bootstrap-signing-op.sh
#   4. source .env.signing && ./scripts/ship-ios.sh

set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

command -v op >/dev/null || { echo "1Password CLI (op) not installed: brew install 1password-cli" >&2; exit 1; }

OP_CONFIG="scripts/.env.signing-op"
[[ -f "$OP_CONFIG" ]] || { echo "Missing $OP_CONFIG — copy scripts/.env.signing-op.example to it and set your vault/item names." >&2; exit 1; }
# shellcheck disable=SC1090
source "$OP_CONFIG"

: "${OP_VAULT:?set OP_VAULT in $OP_CONFIG}"
: "${OP_ITEM:?set OP_ITEM in $OP_CONFIG}"

op vault list >/dev/null 2>&1 || { echo "Not signed in to op. Run: eval \"\$(op signin)\"" >&2; exit 1; }

opread() { op read "op://${OP_VAULT}/${OP_ITEM}/$1"; }

KEY_ID="$(opread "${OP_KEY_ID_FIELD:-key_id}")"
ISSUER_ID="$(opread "${OP_ISSUER_ID_FIELD:-issuer_id}")"
TEAM_ID="$(opread "${OP_TEAM_ID_FIELD:-team_id}")"

KEY_PATH="${HOME}/.appstoreconnect/keys/AuthKey_${KEY_ID}.p8"

# Materialize the .p8 from the item's base64 field only if it isn't already there.
if [[ ! -r "$KEY_PATH" ]]; then
  echo "▸ .p8 not on disk — materializing from 1Password"
  mkdir -p "$(dirname "$KEY_PATH")"
  umask 077
  opread "${OP_AUTH_KEY_B64_FIELD:-auth_key_b64}" | base64 -d > "$KEY_PATH"
  chmod 600 "$KEY_PATH"
  head -1 "$KEY_PATH" | grep -q '^-----BEGIN PRIVATE KEY-----$' \
    || { echo "✗ ${KEY_PATH} is not a valid PEM — check the ${OP_AUTH_KEY_B64_FIELD:-auth_key_b64} field" >&2; exit 1; }
fi

# altool searches a different dir than the .p8's — mirror it there too.
ALTOOL_DIR="${HOME}/.appstoreconnect/private_keys"
mkdir -p "$ALTOOL_DIR"
cp "$KEY_PATH" "$ALTOOL_DIR/AuthKey_${KEY_ID}.p8"
chmod 600 "$ALTOOL_DIR/AuthKey_${KEY_ID}.p8"

umask 077
cat > .env.signing <<EOF
# Generated by scripts/bootstrap-signing-op.sh from 1Password. Do not commit.
export ASC_KEY_ID=${KEY_ID}
export ASC_ISSUER_ID=${ISSUER_ID}
export ASC_KEY_PATH="${KEY_PATH}"
export ASC_TEAM_ID=${TEAM_ID}
EOF

echo "✓ .env.signing written (key ${KEY_ID}, team ${TEAM_ID})"
echo "  Next: source .env.signing && ./scripts/ship-ios.sh"
